version: "3.8"
services:
  api: 
    build: ./api
    container_name: ninja_api_c
    ports: 
      - '5000:5000'
    volumes: 
      - ./api:/app
      - /app/node_modules
  frontend:
    build: ./frontend
    container_name: ninja_frontend_c
    ports:
      - '3030:3030'
    stdin_open: true
    tty: true
